### ISSUE TITLE
Mod breaks controller support

### ISSUE THREAD

**Issue by bradleysimard** [batram/Ultim8_mod#1]
If I use this mod (double checked the vanilla works), none of my controllers are able to do anything ingame.

This includes the "player 1 start" splash screen as well as the lobby where you add players in.

**Comment by batram** [comment]
The [patch to enable InputManager.EnableNativeInput](https://github.com/batram/Ultim8_mod/blob/9a2de24ae53724f70727e510c84a35bf03a28a49/Ultim8_mod/InputManager_Patch.cs) is a bit wonky.
And at the moment it only works properly for me with Steam's Big Picture mode.

What kind of controllers are you using?
Do they all appear in the list of controllers in Steam's Big Picture mode?

**Comment by bradleysimard** [comment]
I have 8 Xbox Series S/X controllers.

They all appear in big picture mode's controller screen.

**Comment by batram** [comment]
At the moment I am using PS4 controllers and [controlloid](https://github.com/experiment322/controlloid-server), but I successfully used Xbox controllers in the past. 

Could you post the contents of the file `output_log.txt` in the game folder?

**Comment by batram** [comment]
Try out [EvenMorePlayers](https://github.com/batram/UCH-EvenMorePlayers) mod.
